Repository canonical/dns-operators, pull requests merged in 2024-04, with the labels that each got.

#4 Add dns_record library
  lib/charms/bind/v0/dns_record.py
  pyproject.toml
  requirements.txt
  tests/unit/test_library_dns_record.py
  tox.ini
Labels: complex, Libraries: OK

#6 Add basic semantic validation for DNS records
  lib/charms/bind/v0/dns_record.py
  tests/unit/test_library_dns_record.py
Labels: trivial, Libraries: OK

#10 Fix lib id
  lib/charms/bind/v0/dns_record.py
Labels: trivial, Libraries: OK

#7 Validate records independently
  lib/charms/bind/v0/dns_record.py
Labels: complex, Libraries: OK

#5 Write initial charm
  .github/workflows/integration_test.yaml
  .licenserc.yaml
  config.yaml
  lib/charms/operator_libs_linux/v2/snap.py
  pyproject.toml
  src-docs/bind.py.md
  src-docs/charm.py.md
  src-docs/constants.py.md
  src-docs/exceptions.py.md
  src/bind.py
  src/charm.py
  src/constants.py
  src/exceptions.py
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_charm.py
  tox.ini
  trivy.yaml
Labels: trivial, Libraries: Out of sync

#11 Abstract the use of secrets from the requirer and provider charms
  lib/charms/bind/v0/dns_record.py
  metadata.yaml
  tests/unit/test_library_dns_record.py
Labels: complex, Libraries: OK

#13 Adapt to the relation interface changes
  lib/charms/bind/v0/dns_record.py
  tests/unit/test_library_dns_record.py
Labels: complex, Libraries: OK

#15 Basic validation of the entries through the lib
  lib/charms/bind/v0/dns_record.py
  tests/unit/test_library_dns_record.py
Labels: complex, Libraries: OK
